services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - JWT_SECRET=im_the_secret
    networks:
      - mynet
  redis:
    image: redis:7-alpine
    container_name: auth_redis
    ports:
      - "6379:6379"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.250.0/24